nodeLinker: node-modules
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-compat.cjs
    spec: '@yarnpkg/plugin-compat'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
yarnPath: .yarn/releases/yarn-3.2.0.cjs
npmRegistryServer: "http://localhost:4873"
npmPublishRegistry: http://localhost:4873
npmAlwaysAuth: true
unsafeHttpWhitelist:
  - localhost
npmScopes:
  cdm:
    npmRegistryServer: http://localhost:4873
    npmPublishRegistry: http://localhost:4873
    npmAlwaysAuth: true